#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-fastercsv
Version  : 1.5.5
Release  : 3
URL      : https://rubygems.org/downloads/fastercsv-1.5.5.gem
Source0  : https://rubygems.org/downloads/fastercsv-1.5.5.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
= Read Me
by James Edward Gray II
== Description
Welcome to FasterCSV.
FasterCSV is intended as a replacement to Ruby's standard CSV library.  It was designed to address concerns users of that library had and it has three primary goals:

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n fastercsv-1.5.5
gem spec %{SOURCE0} -l --ruby > rubygem-fastercsv.gemspec

%build
gem build rubygem-fastercsv.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
fastercsv-1.5.5.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/fastercsv-1.5.5 && ruby -I.:lib:test test/tc_*.rb && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/fastercsv-1.5.5.gem
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/Array/cdesc-Array.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/Array/to_csv-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/add_converter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/add_row-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/add_unconverted_fields-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/build_csv_interface-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/cdesc-FCSV.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/const_missing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/convert_fields-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/dump-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/filter-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/foreach-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/generate-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/generate_line-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/gets-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/header_convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/header_row%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/init_converters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/init_headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/init_parsers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/init_separators-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/instance-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/lineno-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/method_missing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/open-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/parse-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/parse_headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/parse_line-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/puts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/read-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/read-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/readline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/readlines-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/readlines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/rewind-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/shift-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FCSV/table-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/MalformedCSVError/cdesc-MalformedCSVError.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/cdesc-Row.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/delete_if-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/field%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/field-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/field_row%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/fields-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/header%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/header_row%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/include%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/push-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/row-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/to_csv-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Row/values_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/by_col%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/by_col-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/by_col_or_row%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/by_col_or_row-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/by_row%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/by_row-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/cdesc-Table.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/delete_if-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/mode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/push-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/table-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/to_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/to_csv-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/Table/values_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/add_converter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/add_row-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/add_unconverted_fields-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/build_csv_interface-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/cdesc-FasterCSV.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/const_missing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/convert_fields-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/dump-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/filter-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/foreach-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/generate-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/generate_line-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/gets-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/header_convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/header_row%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/init_converters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/init_headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/init_parsers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/init_separators-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/instance-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/lineno-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/method_missing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/open-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/parse-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/parse_headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/parse_line-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/puts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/read-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/read-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/readline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/readlines-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/readlines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/rewind-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/row/cdesc-row.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/shift-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/FasterCSV/table-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/Object/FCSV-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/Object/FasterCSV-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/String/parse_csv-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/page-AUTHORS.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/page-CHANGELOG.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/page-COPYING.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/page-INSTALL.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/page-LICENSE.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/page-README.ri
/usr/lib64/ruby/gems/2.2.0/doc/fastercsv-1.5.5/ri/page-TODO.ri
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/AUTHORS
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/CHANGELOG
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/COPYING
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/INSTALL
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/README
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/TODO
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/examples/csv_converters.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/examples/csv_filter.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/examples/csv_reading.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/examples/csv_table.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/examples/csv_writing.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/examples/purchase.csv
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/examples/shortcut_interface.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/lib/faster_csv.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/lib/fastercsv.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/test/line_endings.gz
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/test/tc_csv_parsing.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/test/tc_csv_writing.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/test/tc_data_converters.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/test/tc_encodings.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/test/tc_features.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/test/tc_headers.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/test/tc_interface.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/test/tc_row.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/test/tc_serialization.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/test/tc_speed.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/test/tc_table.rb
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/test/test_data.csv
/usr/lib64/ruby/gems/2.2.0/gems/fastercsv-1.5.5/test/ts_all.rb
/usr/lib64/ruby/gems/2.2.0/specifications/fastercsv-1.5.5.gemspec
